### ISSUE TITLE
pull in dropbox and caffeine icons from upstream PR

### ISSUE THREAD

**Issue by fossfreedom** [UbuntuBudgie/pocillo#31]
Lets monitor the Moka repository.  There are lots of excellent pull requests that doesn't seem to be being processed.

among them is this https://github.com/snwh/moka-icon-theme/pull/310

lets add this pull request to Pocillo.  Would like to add this as an update to backports.  If by chance Moka gets updated by late July then we can drop this from Pocillo for zesty+1

**Comment by Foggalong** [comment]
This pull request just couldn't go straight into Pocillo because there's a difference in file formats, different file structures, etc. Things could be changed to allow for that but I don't know whether the work would be worth it - would probably be easier just to work in additions on a case by case basis.
